backend/config/routes.rb
Rails.application.routes.draw do

  resources :favorites

  resources :posts

  resources :cors
  match '/', :to => proc {|env| [200, {'Content-Type' => 'text/plain'}, ["Hello world"]] },
        :via => [:get, :post, :put, :delete, :options, :head, :patch]


  get 'user/create'

  get 'user/update'

  get 'user/destroy'

  get 'user/show'

  get 'user/index'

  get '/user/get/:name', to: "user#find_by_name"

  post '/posts/new', to: "posts#create"

  post '/posts/new_post', to: "posts#new_post"

  get '/userPosts/:name', to: "posts#user_posts"

  get '/count/posts', to: "posts#count"

  get 'user/is_following/:id', to: "user#following?"

  resources :user do
    member do
      get :following, :followers
    end
  end

  post 'relationships/create', to: "relationships#create"

  delete 'relationships/:id', to: "relationships#destroy"

  controller :user, path: '/user' do
    match 'create', via: [ :post, :options]
  end


  controller :auth, path: '/auth' do
    match 'authenticate', via: [ :post ]
  end

  post '/upload_avatar', to: "user#upload"

  post '/posts/new', to: "posts#create"


  post '/favorites/create', to: "favorites#create"

  get '/getFavorites/:id', to: "favorites#index"

  get '/is_favorite/:id', to: "user#favorite?"

  delete 'favorites/:id', to: "favorites#destroy"


end

backend/app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  belongs_to :post, class_name: "Post"
  validates :user_id, presence: true
  validates :post_id, presence: true
end

backend/app/controllers/favorites_controller.rb
class FavoritesController < Api::BaseController
  before_filter :authenticate, :only => [:index, :create, :destroy]
  respond_to :json

  def index
    @favorites = Favorite.where(user_id: params[:id])
    render json: @favorites.as_json(:include => {:post => {
                                        :include  => :user
                                    }})
  end

  def show
    respond_with(@favorite)
  end

  def new
    @favorite = Favorite.new
    respond_with(@favorite)
  end

  def edit
  end


  def create
    @favorite = Favorite.new(post_id: params[:post_id], user_id: @current_user.id)
    if @favorite.save
      render json: {success: true}
    else
      render json: {success: false}
    end
  end

  def update
    @favorite.update(favorite_params)
    respond_with(@favorite)
  end



  def destroy
    @favorite = Favorite.find_by(user_id: @current_user.id, post_id: params[:id])
    render json: Favorite.destroy(@favorite.id)
  end

  private
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    def favorite_params
      params[:favorite]
    end
end

backend/app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

backend/app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

backend/app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

backend/app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>